/*
 * Rose, Raj, Sophie
 * August 18th, 2023
 * The program we created offers school administrators a comprehensive and user-friendly interface for logging school data. 
 * With our program, admin can seamlessly input, update, and manage both employee and student information all in one, secure platform. 
 * This system will be able to add, edit, search, remove and list details about students and employees that exist in their database. 
 * The program also offers a database for storing school inventory, and the ability to add, edit, remove and list items in the inventory. 

 * This frame is the main page. 
 */

import javax.swing.JOptionPane;


public class FrmMainPage extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainPage
     */
    public FrmMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmployee = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblInstruction = new javax.swing.JLabel();
        btnInventory = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Page");
        setName("FrmMainPage"); // NOI18N
        setPreferredSize(new java.awt.Dimension(415, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        btnEmployee.setText("Employee Data");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmployee);
        btnEmployee.setBounds(6, 135, 120, 23);

        btnStudent.setText("Student Data");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudent);
        btnStudent.setBounds(142, 135, 115, 23);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitle.setText("School Database");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(155, 9, 120, 16);

        btnHelp.setText("?");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp);
        btnHelp.setBounds(360, 6, 35, 23);

        lblInstruction.setText("This program will store the school's data. ");
        getContentPane().add(lblInstruction);
        lblInstruction.setBounds(90, 35, 250, 16);

        btnInventory.setText("Inventory Data");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventory);
        btnInventory.setBounds(275, 135, 120, 23);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(170, 210, 55, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainPageBackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        new FrmEmployeePage().setVisible(true);//open the employee page
        this.dispose();//close the main page
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        new FrmStudentPage().setVisible(true);//open the student page
        this.dispose();//close the main page
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Press the Employee Data button to enter the employee information database,\nthe Student Data button to enter the student information database\nor the Inventory Data to enter the inventory database. ");//instructions for the user
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        new FrmInventoryPage().setVisible(true);//open the inventory page
        this.dispose();//close the main page
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // exit the program
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInstruction;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
